services:
    dev:
        hostname: django-gdpr-manager
        build:
            target: dev # NOTE: this is the "stage" in the Dockerfile
            context: .
        profiles:
          - dev
        stdin_open: true
        tty: true
        volumes:
            - .:/src
            # Mount empty volume in venv to ignore
            - /src/venv/
    release:
      build:
        target: release
      profiles:
        - release
      stdin_open: true
      tty: true
      volumes:
        - .:/src
        - /src/venv
