# Generated by Django 4.2.11 on 2024-10-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdpr_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GDPRTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("tenant_email", models.EmailField(max_length=254)),
                ("personal_info", models.TextField()),
            ],
        ),
    ]
