# Generated by Django 4.2.11 on 2024-10-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdpr_manager", "0002_gdprtestmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GDPRTestModel",
        ),
    ]
