# Generated by Django 4.2.16 on 2024-11-03 04:23

from django.db import migrations, models
import gdpr_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithCustomSearchNotesField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField()),
                ('notes', models.TextField()),
            ],
            bases=(models.Model, gdpr_manager.models.GDPRModel),
        ),
        migrations.CreateModel(
            name='ModelWithGDPRMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_personal_info', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField()),
            ],
            bases=(models.Model, gdpr_manager.models.GDPRModel),
        ),
        migrations.CreateModel(
            name='ModelWithMultipleFieldsToSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField()),
                ('host_id', models.IntegerField()),
            ],
            bases=(models.Model, gdpr_manager.models.GDPRModel),
        ),
        migrations.CreateModel(
            name='ModelWithoutGDPRMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_personal_info', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=(models.Model, gdpr_manager.models.GDPRModel),
        ),
        migrations.CreateModel(
            name='ModelWithoutGDPRSubclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_personal_info', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithoutGDPRSubclassOrMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_personal_info', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithSingleFieldsToSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField()),
            ],
            bases=(models.Model, gdpr_manager.models.GDPRModel),
        ),
    ]
