# Generated by Django 4.2.16 on 2024-11-03 05:47

from django.db import migrations, models
import gdpr_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithShowWarningIfFoundFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField()),
            ],
            bases=(models.Model, gdpr_manager.models.GDPRModel),
        ),
        migrations.CreateModel(
            name='ModelWithShowWarningIfFoundTrue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField()),
            ],
            bases=(models.Model, gdpr_manager.models.GDPRModel),
        ),
    ]
